# Generated by Django 3.2.9 on 2022-09-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TOdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_Date', models.DateTimeField()),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
